### PR TITLE
Make E2 Functions also move the console controls

### PR DESCRIPTION
**Pull request by noatblok**
Added a new function called `TARDIS:UsePart`, when called, it plays the control animation alongside the sound. Added `UsePart` to the `HandleE2` events.

### CODE REVIEW

**Comment by parar020100** [comment]
I have a slight issue with the way this function works
`TARDIS:GetPartByAction(ent, action)`

Seems like it presumes there's only one part per action
Right now many TARDISes have several parts with same controls
Is a random one gonna be selected in this?

**Comment by noatblok** [comment]
I haven't actually tested that, at the moment it just looks through the interior controls, and finds the first one that triggers the corresponding action (HADS, Cloak, etc.). I'm not sure what the best way to resolve this is, my only idea is to add some sort of argument to let the E2 code choose which control (If there are more than one).

**Comment by parar020100** [comment]
I can also see `TARDIS:UsePart(part)` cause potential issues with `PART:Use()` functions specified.
For instance, that function may specify the delays and additional effects & part interactions

I think we should stick to #885 and make extension creators choose which parts should be toggled.
Not finding and moving them automatically.

**Comment by AmyJeanes** [comment]
Hey, due to inactivity and the fact this PR would need significant work to be accepted, I am going to close this for now. If you pick this up again please feel free to raise a new PR.

**Pull request closed without merging**
