### PR TITLE
Old mat and demat drum beat

### PR DESCRIPTION
**Pull request by PoogieTheGoose**
So....
I changed mat,demat and full sounds with replaced drums in them(2010 drum beat ---> 1963-2005 drum beat).The reason for it is that many TARDIS extensions use base addon sounds and most of them are older interior ones(1983, etc) and it would be more easer to have two sound variants in the base addon(default being the old drum)so the old TARDISes will have it as default and the ones who want 2010 drum will just have to change the sound file path.It would be really nice if you accept those sounds and fade sequence for them(to make them more smoother for the sounds).
P.s:
I also changed mat fail sound, so it wont have this ugly vorp sound in the end

### CODE REVIEW

**Comment by parar020100** [comment]
I'll listen to the sounds later
But anyway, I think the default interior's sounds need to stay
If you're changing the ones in base.lua, you need to restore the existing ones in default.lua

**Comment by PoogieTheGoose** [comment]
> I'll listen to the sounds later But anyway, I think the default interior's sounds need to stay If you're changing the ones in base.lua, you need to restore the existing ones in default.lua

Done

**Comment by parar020100** [comment]
Demat: all ok

image

**Comment by parar020100** [comment]
Full flight: ok

image

**Comment by parar020100** [comment]
Mat: 0.5 seconds offset (?)

image

**Comment by parar020100** [comment]
mat_fail: has been made much better (with that junk lost at the end)

image

**Comment by parar020100** [comment]
mat_fast: ok

image

**Comment by parar020100** [comment]
mat_fast_damaged: ok

image

**Comment by parar020100** [comment]
Mat has been fixed
I've double-checked the sounds in the game
All works fine for me, can be merged

**Review by AmyJeanes — APPROVED** [review]

**Pull request merged**
