### PR TITLE
TARDIS Interface improvements

### PR DESCRIPTION
**Pull request by parar020100**
- The interior can now be chosen from the options in the right menu (much faster than 7 clicks in the interface)
- The controls of the door and the lock have been moved to the virtual console menu (no point for them having whole seperate screens). They remain animated and change text according to the status

For all questions: contact parar020100#5894 in Discord

Preview: 

Garry's Mod 13 02 2021 20_15_13

изображение
изображение
изображение

### CODE REVIEW

**Comment by MattJeanes** [comment]
This looks great, I fully agree changing the interior currently is a pain and is one of the things that makes sense to exist outside of the main console interface as well. As for the lock and door controls completely agree too, they just happened to exist before the virtual console and never really considered moving them over.

I will review the code and test things later on today, thank you for your contribution!

**Comment by parar020100** [comment]
> 
> 
> This looks great, I fully agree changing the interior currently is a pain and is one of the things that makes sense to exist outside of the main console interface as well. As for the lock and door controls completely agree too, they just happened to exist before the virtual console and never really considered moving them over.
> 
> I will review the code and test things later on today, thank you for your contribution!

Sorry for writing here, could you please allow me to message you on Discord?
There's something I would like to discuss about one more thing I can do
parar020100#5894

**Comment by francodml** [comment]
I agree this is an improvement over browsing through to the settings menu, especially in multiplayer, where higher latencies make it difficult to properly use the 3D2D interface.

**Comment by parar020100** [comment]
Closing this request due to creation of the branches for these features in the repository

**Pull request closed without merging**
